//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPI_AOI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float DPI {
            get {
                return ((float)(this["DPI"]));
            }
            set {
                this["DPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 400")]
        public global::System.Drawing.Size FOV {
            get {
                return ((global::System.Drawing.Size)(this["FOV"]));
            }
            set {
                this["FOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.3.100")]
        public string PLC_IP {
            get {
                return ((string)(this["PLC_IP"]));
            }
            set {
                this["PLC_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int PLC_PORT {
            get {
                return ((int)(this["PLC_PORT"]));
            }
            set {
                this["PLC_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M301")]
        public string PLC_BIT_GO_UP_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_UP_TOP"]));
            }
            set {
                this["PLC_BIT_GO_UP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M300")]
        public string PLC_BIT_GO_DOWN_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_DOWN_TOP"]));
            }
            set {
                this["PLC_BIT_GO_DOWN_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M303")]
        public string PLC_BIT_GO_LEFT_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_LEFT_TOP"]));
            }
            set {
                this["PLC_BIT_GO_LEFT_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M302")]
        public string PLC_BIT_GO_RIGHT_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_RIGHT_TOP"]));
            }
            set {
                this["PLC_BIT_GO_RIGHT_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_BIT_GO_HOME {
            get {
                return ((string)(this["PLC_BIT_GO_HOME"]));
            }
            set {
                this["PLC_BIT_GO_HOME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D208")]
        public string PLC_REG_SPEED_TOP {
            get {
                return ((string)(this["PLC_REG_SPEED_TOP"]));
            }
            set {
                this["PLC_REG_SPEED_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1002")]
        public string PLC_REG_X_TOP {
            get {
                return ((string)(this["PLC_REG_X_TOP"]));
            }
            set {
                this["PLC_REG_X_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1000")]
        public string PLC_REG_Y_TOP {
            get {
                return ((string)(this["PLC_REG_Y_TOP"]));
            }
            set {
                this["PLC_REG_Y_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1006")]
        public string PLC_REG_X_BOT {
            get {
                return ((string)(this["PLC_REG_X_BOT"]));
            }
            set {
                this["PLC_REG_X_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1004")]
        public string PLC_REG_Y_BOT {
            get {
                return ((string)(this["PLC_REG_Y_BOT"]));
            }
            set {
                this["PLC_REG_Y_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M600")]
        public string PLC_BIT_ERROR_MACHINE {
            get {
                return ((string)(this["PLC_BIT_ERROR_MACHINE"]));
            }
            set {
                this["PLC_BIT_ERROR_MACHINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_BIT_ERROR_MACHINE_CONFIRM {
            get {
                return ((string)(this["PLC_BIT_ERROR_MACHINE_CONFIRM"]));
            }
            set {
                this["PLC_BIT_ERROR_MACHINE_CONFIRM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M100")]
        public string PLC_BIT_HAS_PRODUCT_TOP {
            get {
                return ((string)(this["PLC_BIT_HAS_PRODUCT_TOP"]));
            }
            set {
                this["PLC_BIT_HAS_PRODUCT_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M101")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_TOP {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_TOP"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M102")]
        public string PLC_BIT_GO_COORDINATES_FINISH_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_TOP"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M112")]
        public string PLC_BIT_PRODUCT_FAIL {
            get {
                return ((string)(this["PLC_BIT_PRODUCT_FAIL"]));
            }
            set {
                this["PLC_BIT_PRODUCT_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M113")]
        public string PLC_BIT_PRODUCT_PASS {
            get {
                return ((string)(this["PLC_BIT_PRODUCT_PASS"]));
            }
            set {
                this["PLC_BIT_PRODUCT_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M3")]
        public string PLC_BIT_DOOR_STATUS {
            get {
                return ((string)(this["PLC_BIT_DOOR_STATUS"]));
            }
            set {
                this["PLC_BIT_DOOR_STATUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_BIT_MACHINE_STATUS {
            get {
                return ((string)(this["PLC_BIT_MACHINE_STATUS"]));
            }
            set {
                this["PLC_BIT_MACHINE_STATUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M105")]
        public string PLC_BIT_HAS_PRODUCT_BOT {
            get {
                return ((string)(this["PLC_BIT_HAS_PRODUCT_BOT"]));
            }
            set {
                this["PLC_BIT_HAS_PRODUCT_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_BIT_CONTROL_RUN {
            get {
                return ((string)(this["PLC_BIT_CONTROL_RUN"]));
            }
            set {
                this["PLC_BIT_CONTROL_RUN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_BIT_READ_QRCODE_FAIL {
            get {
                return ((string)(this["PLC_BIT_READ_QRCODE_FAIL"]));
            }
            set {
                this["PLC_BIT_READ_QRCODE_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_BIT_CAPTURE_FAIL {
            get {
                return ((string)(this["PLC_BIT_CAPTURE_FAIL"]));
            }
            set {
                this["PLC_BIT_CAPTURE_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string LIGHT_COM {
            get {
                return ((string)(this["LIGHT_COM"]));
            }
            set {
                this["LIGHT_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M321")]
        public string PLC_BIT_GO_UP_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_UP_BOT"]));
            }
            set {
                this["PLC_BIT_GO_UP_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M320")]
        public string PLC_BIT_GO_DOWN_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_DOWN_BOT"]));
            }
            set {
                this["PLC_BIT_GO_DOWN_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M323")]
        public string PLC_BIT_GO_LEFT_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_LEFT_BOT"]));
            }
            set {
                this["PLC_BIT_GO_LEFT_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M322")]
        public string PLC_BIT_GO_RIGHT_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_RIGHT_BOT"]));
            }
            set {
                this["PLC_BIT_GO_RIGHT_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M341")]
        public string PLC_BIT_GO_UP_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_UP_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_UP_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M340")]
        public string PLC_BIT_GO_DOWN_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_DOWN_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_DOWN_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1008")]
        public string PLC_REG_CONVEYOR {
            get {
                return ((string)(this["PLC_REG_CONVEYOR"]));
            }
            set {
                this["PLC_REG_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D228")]
        public string PLC_REG_SPEED_BOT {
            get {
                return ((string)(this["PLC_REG_SPEED_BOT"]));
            }
            set {
                this["PLC_REG_SPEED_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D246")]
        public string PLC_REG_SPEED_CONVEYOR {
            get {
                return ((string)(this["PLC_REG_SPEED_CONVEYOR"]));
            }
            set {
                this["PLC_REG_SPEED_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M106")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_BOT {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_BOT"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M107")]
        public string PLC_BIT_GO_COORDINATES_FINISH_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_BOT"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M140")]
        public string PLC_BIT_GO_COORDINATES_FINISH_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M110")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string AUTOSCAN_COM {
            get {
                return ((string)(this["AUTOSCAN_COM"]));
            }
            set {
                this["AUTOSCAN_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D0")]
        public string PLC_REG_PASSWORD {
            get {
                return ((string)(this["PLC_REG_PASSWORD"]));
            }
            set {
                this["PLC_REG_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M316")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_TOP {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_TOP"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M336")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_BOT {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_BOT"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M354")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M121")]
        public string PLC_BIT_GO_COORDINATES_FINISH_SETUP_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_TOP"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M122")]
        public string PLC_BIT_GO_COORDINATES_FINISH_SETUP_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_BOT"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M120")]
        public string PLC_BIT_GO_COORDINATES_FINISH_SETUP_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_CONVEYOR"] = value;
            }
        }
    }
}
